services:
  - type: web
    name: stepout-buffalo-scraper
    env: node
    buildCommand: |
      npm install
      npm rebuild puppeteer
      npm run postinstall
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/chromium-browser"
    buildFilter:
      paths:
        - package.json
        - package-lock.json 